journals page made responsive, align journals form and heading in the center
codeisscience/journal-policy-tracker-frontend pull request #104
Opened 2022-04-05 15:26 UTC by vedeepika

### Issues Fixed

1). The form and heading of the journal page were not in the center. I aligned the form and heading in the center. 

![Screenshot (54)](https://user-images.githubusercontent.com/88725279/161788673-b3d75950-3d97-40a6-ac2d-3778a4040e0e.png)

2). I Made the Journals page responsive on all the devices.

![Screenshot (55)](https://user-images.githubusercontent.com/88725279/161788742-8d292efc-1d89-45d9-b5de-ab95f8587358.png)

3). I put some margin on the heading from the top. because the heading was touching the navbar.

![Screenshot (55)](https://user-images.githubusercontent.com/88725279/161788742-8d292efc-1d89-45d9-b5de-ab95f8587358.png)

## Type of change

- [ ] New feature (non-breaking change which adds functionality).

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding tests.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

2022-04-06 09:45 UTC, padmajabhol requested changes

2022-04-06 09:45 UTC, padmajabhol commented on src/pages/Journal.js
> +
I don't think we need the white spaces here.

2022-04-06 09:45 UTC, padmajabhol commented on src/pages/Journal.js
> +
I don't think we need the white spaces here.

2022-04-06 09:45 UTC, padmajabhol commented on src/styles/Login.css
> +
Remove the extra white-space

2022-04-06 10:31 UTC, vedeepika reviewed
Removed whitespace.

2022-04-07 05:36 UTC, padmajabhol approved these changes

2022-04-11 14:50 UTC, merged